spring:
  application:
    name: ${APPLICATION_NAME:CarDealership}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
  show-sql: ${JPA_SHOW_SQL:true}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3308}/${DATABASE_NAME:database}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Sqlwer}

logging:
  level:
    org:
      hibernate:
        SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        transaction: ${LOGGING_LEVEL_SPRING_TRANSACTION:DEBUG}




#  docker run --name CarDetails -p 3308:3306 -e MYSQL_ROOT_PASSWORD=Sqlwer -e MYSQL_DATABASE=database -d mysql

